.libPaths("/Users/demian/lib/R_lib")
install.packages(c("car", "haven","dplyr","stringr","tidyverse","ggplot2","glue","tibble","ggpubr","cowplot","writexl","tidyr"))
library(car)
library(haven)
library(dplyr)
library(stringr)
library(tidyverse)
library(ggplot2)
library(glue)
library(tibble)
library(ggpubr)
library(cowplot)
library(writexl)
library(tidyr)
#practice from textbook statistical learning chapter 11 Survival Analysis
install.packages(c("ISLR2","survival"))
library(ISLR2)
names(BrainCancer)
attach(BrainCancer)
table(sex)
table(diagnosis)
table(status)
table(time)
library(survival)
fit.surv<-survfit(Surv(time,status)~1)
plot(fit.surv, xlab="Months", ylab="Estimated Probability of Survival")
fit.sex<-survfit(Surv(time,status)~sex)
plot(fit.sex, xlab="Months", ylab="Estimated Probability of Survival", col=c(2,4))
legend("bottomleft", levels(sex), col = c(2,4), lty = 1)
